version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: weather_db
      POSTGRES_USER: ctva
      POSTGRES_PASSWORD: ctva
    ports:
      - "5432:5432"
    volumes:
      - ./ctva_ddl.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: ./
    environment:
      - FLASK_APP=main.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    healthcheck:
        test: ["CMD-SHELL", "curl --fail --silent http://localhost:5000/health | grep UP || exit 1"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 20s


